### PR TITLE
feat: add bitnami/common with compatibility.openshift.adaptSecurityContext

### PR DESCRIPTION
**Pull request by minijus**
Closes: https://github.com/renovatebot/helm-charts/issues/1701

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
I would prefer a compatibility option like the bitnami charts use

https://github.com/bitnami/charts/tree/main/bitnami/cert-manager#global-parameters

**Comment by minijus** [comment]
> I would prefer a compatibility option like the bitnami charts use
> 
> https://github.com/bitnami/charts/tree/main/bitnami/cert-manager#global-parameters

Should the value name be exactly the same as in Bitnami charts `global.compatibility.openshift.adaptSecurityContext`?

Would it be enough to have it as boolean?
Or should it have `auto`|`force`|`disabled` options (as in Bitnami)? If yes, would adding `bitnami/common` dependency to the chart be preferred way? Or should [helper method to detect OpenShift](https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_compatibility.tpl#L8-L17) be copy/pasted (with attribution)?

**Comment by viceice** [comment]
I think it's ok to use the bitnami common chart because we already have it as transitive dependency

**Review by viceice — COMMENTED** [review]
please don't force push

**Comment by minijus** [comment]
> please don't force push 

Is there anything I should change/update now because I forced pushed before?

**Comment by minijus** [comment]
@viceice , could you have a look at this again?

**Review by viceice — APPROVED** [review]

**Comment by minijus** [comment]
Thank you @viceice !

**Pull request merged**
