### PR TITLE
feat: Add cronjob completions and parallelism options

### PR DESCRIPTION
**Pull request by wrighbr**
Introduce new configurable options for defining the number of successful completions needed before marking a job complete and specifying the number of pods to run in parallel. This change enhances flexibility in managing cronjobs efficiently.

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
please add a test

**Comment by wrighbr** [comment]
> please add or modify a test
> 
> https://github.com/renovatebot/helm-charts/tree/main/charts/renovate/ci

@viceice I've added a basic test

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
will be released with next renovate release

**Comment by viceice** [comment]
do not merge, you'll block automerge.

**Comment by viceice** [comment]
it seems you need to validate the kubernetes version, your changes will break on older kubernetes

**Comment by viceice** [comment]
please no force push

**Review by viceice — APPROVED** [review]

**Pull request merged**
