### PR TITLE
fix: Fixed helm-docs download url

### PR DESCRIPTION
**Pull request by kvanzuijlen**

### CODE REVIEW

**Comment by viceice** [comment]
will first ask at helm docs repo if the file name change was intentional

**Comment by kvanzuijlen** [comment]
Looks like https://github.com/norwoodj/helm-docs/commit/297d05b88f00cf987d7faf7bfc413d6933243bef is the commit that broke it.

**Comment by kvanzuijlen** [comment]
@viceice seems to have been unintentional: https://github.com/norwoodj/helm-docs/issues/200

**Comment by viceice** [comment]
closing for now until the helm-docs maintainer decide a solution

**Pull request closed without merging**
