### PR TITLE
fix: allow fsGroup to be set to null instead of defaulting it to 1000

### PR DESCRIPTION
**Pull request by TadasButkevicius**
#### Problem:
Currently, when caching is enabled, the pod's `securityContext` defaults the `fsGroup` to `1000`, even if it is explicitly set to `null`. This behavior can conflict with environments like OpenShift, which uses **Security Context Constraints (SCCs)** to automatically manage certain security context fields (e.g., `runAsUser`, `fsGroup`, `seLinuxOptions`).

In OpenShift's **restricted SCC**, these fields are enforced to ensure pods run with minimal privileges, and manually setting them may cause issues or break security compliance. In such cases, the `securityContext` should not be explicitly set or should allow fields like `fsGroup` to be left as `null`.

#### Solution:
This change ensures that the `fsGroup` value can be explicitly set to `null` within the `securityContext` without defaulting to `1000`. The new behavior will be as follows:

```yaml
securityContext:
  fsGroup: ~

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
please provide a sample values file to show usage

**Comment by TadasButkevicius** [comment]
Hey, thanks for review.

```
securityContext:
  fsGroup: ~
renovate:
  persistence:
    cache:
      enabled: true
  config: |
    {}
```

in template this would allow to set `fsGroup` to `null`
```
...
securityContext:
  fsGroup: null
```

instead of currently defaulting it to `1000` even if its set but set to null
```
...
securityContext:
  fsGroup: 1000
```

**Comment by TadasButkevicius** [comment]
> please provide a sample values file to show usage

@viceice should I commit this as a test, or is the explanation provided sufficient?

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
> > please provide a sample values file to show usage
> 
> @viceice should I commit this as a test, or is the explanation provided sufficient?

yes, add it to one of the existing tests.

**Comment by TadasButkevicius** [comment]
> > > please provide a sample values file to show usage
> > 
> > 
> > @viceice should I commit this as a test, or is the explanation provided sufficient?
> 
> yes, add it to one of the existing tests.

added

**Comment by TadasButkevicius** [comment]
@viceice can we get this merged?

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
test failure

**Comment by TadasButkevicius** [comment]
> test failure

okey, missed the part where it actually installs the helm charts. 

So basically now its testing that one case where `fsGroup` shoudn't be null because its not restricted SCC where charts are being installed and i guess it doesn't like the null value here.

I can leave:

```
persistence:
    cache:
      enabled: true
```

but i need to remove:

```
securityContext:
  fsGroup: ~
```

removing `securityContext` it would default to `fsGroup: 1000` for this ci.


And this only should be set for restricted SCC:

```
securityContext:
  fsGroup: ~
```

**Review by viceice — APPROVED** [review]

**Comment by TadasButkevicius** [comment]
so looks like smth with pvc all together, can't enable it, probably that's why it wasn't there at first place

**Comment by minijus** [comment]
This would address https://github.com/renovatebot/helm-charts/issues/1701.

Thanks @TadasButkevicius!

**Review by viceice — COMMENTED** [review]
replaced by
- #1782

**Pull request closed without merging**
