### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by emirot**

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Comment by emirot** [comment]
Probably need to update the chart version to make the build pass?
https://github.com/renovatebot/helm-charts/runs/3203685516

**Comment by viceice** [comment]
Nope, we are in sync with renovate versions, so we need to wait for next release.  Should be today or tomorrow. 🤗

**Comment by emirot** [comment]
Ok thank you @viceice 
I do have a question regarding this repo, because I also found this helm chart: https://github.com/whitesource/renovate-on-prem.
It looks like they accomplish the same thing but their implementation is different.
I would like to pick the right solution for our use case.
I can share more with you regarding my use case on private messages.

**Comment by viceice** [comment]
@emirot This chart is using the open source renovate cli internally. The other uses the whitesource on-premise renovate version.

For more info ask in the appropriate repo's discussions.

**Pull request merged**
