### PR TITLE
Update helm repository index for bitnami deps

### LINKED ISSUE #218: Bitnami Redis Dependency has been removed from Bitnami chart index
# Summary
Yesterday, [Bitnami removed chart versions older than 6 months from the bitami Helm Chart index](https://github.com/bitnami/charts/issues/10539), which means the Bitnami Helm chart [dependency](https://github.com/renovatebot/helm-charts/blob/add92977b4857c301090dd02b99a327849622edb/charts/renovate/Chart.yaml#L35) for the Renovatebot helmchart is now no longer resolvable.

## Quick Fix
Update the version of the Redis dependency, [as renovate suggested](https://github.com/renovatebot/helm-charts/pull/189) ;)

### PR DESCRIPTION
**Pull request by chaospuppy**
resolves #218 using [bitnami's suggested workaround](https://github.com/bitnami/charts/issues/10539)

### CODE REVIEW

**Comment by JamieMagee** [comment]
Some more incentive for me to complete #189 😓

**Review by JamieMagee — APPROVED** [review]

**Review by viceice — CHANGES_REQUESTED** [review]
you can't change the version manually

**Comment by chaospuppy** [comment]
@viceice I removed the manual version bump

**Comment by viceice** [comment]
i like to see a migration to latest Redis instead of this workaround

**Comment by aslafy-z** [comment]
Can this PR be merged and released until the other passes tests?

**Comment by viceice** [comment]
nope, working on a fix now

**Pull request closed without merging**
