### PR TITLE
fix: `RENOVATE_CONFIG_FILE` not being rendered

### LINKED ISSUE #173: Renovate config is not correctly read on v30
As reported originally here: https://github.com/renovatebot/renovate/issues/13054

Copypaste from my comment here: https://github.com/renovatebot/renovate/issues/13054#issuecomment-991641145:

> 
> I believe this could be related to:
> 
> > config: Renovate will now fail if RENOVATE_CONFIG_FILE is specified without a file extension
> 
> (https://github.com/renovatebot/renovate/releases/tag/30.0.0)
> 
> This should have been fixed here: https://github.com/renovatebot/helm-charts/pull/170
> 
> But unfortunately the line introduced in that PR will not be evaluated because the whole `env` section is guarded by another if: https://github.com/renovatebot/helm-charts/blob/5e50b02fcc60139538e07e1079464ce0fa9ddb6a/charts/renovate/templates/cronjob.yaml#L88
> 
> As a workaround, this can be specified in the `values.yml`
> 
> ```
>   env:
>     RENOVATE_CONFIG_FILE: /usr/src/app/config.json
> ```

### PR DESCRIPTION
**Pull request by roobre**
- Fixes #173
- Fixes https://github.com/renovatebot/renovate/issues/13054
- regression of #170

### CODE REVIEW

**Comment by roobre** [comment]
Personally I'd rather get rid of such a massively complex `if` clause, as it can easily hide bugs like this one, but I preferred to keep the PR simple.

**Comment by viceice** [comment]
> Personally I'd rather get rid of such a massively complex `if` clause, as it can easily hide bugs like this one, but I preferred to keep the PR simple.

Thanks, can you refactor the condition in another pr after this?

**Review by viceice — APPROVED** [review]

**Comment by roobre** [comment]
@viceice Sure, let me give it a try :)

**Comment by viceice** [comment]
> @viceice Sure, let me give it a try :)

Thanks, please try to use semantic commit messages or simply push miltiple commits to pass `Semantic Pull Request` check 😉

**Comment by viceice** [comment]
This will be published with next renovate release, see #54 for reason

**Comment by roobre** [comment]
Awesome, thanks for the quick review!

I've created a draft getting rid of the `if` entirely here: https://github.com/renovatebot/helm-charts/pull/175

There are more complex options available but personally I'm not sure if they are worth the added complexity. I'll be happy to hear your thoughts!

**Pull request merged**
