### PR TITLE
ci: Added checks for 1.25 & 1.26 and removed checks for 1.20

### LINKED ISSUE #265: add kubernetes 1.25 to tests

### PR DESCRIPTION
**Pull request by kvanzuijlen**
- Closes #265

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
please also add 1.26 if possible

**Comment by kvanzuijlen** [comment]
1.21 will go EOL end of this month (at least on GKE). I could remove that one as well, or open a separate PR for it?

EKS 1.21 is EOL 2023-02-15
GKE 1.21 is EOL 2023-01-31
AKS 1.21 is EOL 2022-07-31

**Review by viceice — APPROVED** [review]
let's wait for v1.21 EOL and do in separate PR

**Comment by JamieMagee** [comment]
FYI I found this website useful to show supported versions:
- [Amazon EKS - endoflife.date](https://endoflife.date/amazon-eks)
- [Azure Kubernetes Service - endoflife.date](https://endoflife.date/azure-kubernetes-service)
- [Google Kubernetes Engine - endoflife.date](https://endoflife.date/google-kubernetes-engine)

**Comment by kvanzuijlen** [comment]
@JamieMagee I found the same website, but for GKE the dates were incorrect so I decided to double-check all of them (and opened https://github.com/endoflife-date/endoflife.date/pull/2295).

**Pull request merged**
