### PR TITLE
feat: Add support for private custom image

### PR DESCRIPTION
**Pull request by Djiit**
Hey 👋 ,

I need to be able to use my own custom Renovate image (Mostly for injecting a `.nprmc`). A great way to do this would be to be able to use my own image, from my private registry.

To do this, I need to inject an `imagePullSecrets` into the spec of the cronjob. This PR resolves this.

How should I test my changes?

Thanks!

### CODE REVIEW

**Review by viceice — APPROVED** [review]
Instead of writing your `npmrc` to the image, you could simply mount it as volume or pass it via `config.js` or `RENOVATE_NPMRC` env.

https://docs.renovatebot.com/configuration-options/#npmrc

**Review by viceice — CHANGES_REQUESTED** [review]
The readme needs to be updated with the new settings, see docs lint logs

**Comment by JamieMagee** [comment]
I agree with @viceice that you don't need to create a custom image just to add your own `.npmrc`, however this change should help users switch to private docker registries now that Docker Hub has put rate limits in place.

**Comment by Djiit** [comment]
Hey, 

Thanks for your suggestions. @viceice, I'll definitely try this.
Let me update the docs so you can merge this.

**Comment by Djiit** [comment]
Don't merge this for now; I'm having some issues locally. i'll request review when I'm done

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
@JamieMagee should we bump the version to get a release when merging this?

**Comment by viceice** [comment]
This should be usable with next renovate release

**Pull request merged**
