### PR TITLE
fix: wrong readme

### PR DESCRIPTION
**Pull request by viceice**
* fix readme
* diable version lint (no version change would be a noop, so changes would be published by next bump)

ref #52 #54 #55

### CODE REVIEW

**Comment by viceice** [comment]
@JamieMagee Should the removed readme line be readded to the template instead?

**Comment by JamieMagee** [comment]
No, it's not really relevant to the chart itself. It's more related to the `helm-docs` tool. I think this is correct.

**Comment by viceice** [comment]
So are you fine with this changes?

**Comment by JamieMagee** [comment]
Yup. I'll merge :+1:

**Review by JamieMagee — APPROVED** [review]

**Pull request merged**
