### PR TITLE
feat: allow api version override

### LINKED ISSUE #145: ArgoCD:  "You must have atleast batch/v1beta1 to use CronJob"
Unfortunately, this PR broke deployment with ArgoCD, as it only tells Helm that `batch/v1` is available (by specifying `--api-versions batch/v1` as an argument to `helm template`). This results in the "You must have atleast batch/v1beta1 to use CronJob" error.

I don't know if this should be fixed here, but this chart is the only one I know that has this problem. Would it be fine to only check for `batch/v1beta1` or `batch/v1` respectively instead of `batch/v1/CronJob`?

_Originally posted by @timoschwarzer in https://github.com/renovatebot/helm-charts/issues/144#issuecomment-888322276_

### PR DESCRIPTION
**Pull request by viceice**
- Allow api version override
- Simply api version check
- Add some docs

closes #145

### CODE REVIEW

**Comment by ekeih** [comment]
Hi, thanks for implementing this override @viceice! I just wanted to use `helm template` with this chart and was very happy to see that this change just got merged three hours ago 🙂
If I am not mistaken this release is not available at https://docs.renovatebot.com/helm-charts, is this on purpose? 🤔 (Maybe some automation didn't like the `renovate-25.64.1+1` instead of `renovate-25.64.2`? 😄)

**Comment by ekeih** [comment]
https://github.com/renovatebot/helm-charts/releases/tag/renovate-25.65.0 seems to be publised to the helm repository now. Not sure if that was in response to this comment or not, but either way your work is greatly appreciated and the release seems to work! Thanks 🙂

**Comment by viceice** [comment]
We currently follow the main renovate versions, so i can only publish the chart with a sub version `+1` but the chart-releaser tool won't publish it to the gh-pages 😕 

Maybe some knows better tooling for automated helm chart releasing. Currently all we need to do is to wait for next automatic renovate release, which will be multiple times a day

**Comment by viceice** [comment]
see also #54

**Comment by ekeih** [comment]
I see, thanks for the explanation @viceice! Normally, waiting for the next automated release should be fine, yesterday I was just trying to use it too fast :)

**Pull request merged**
